### ISSUE TITLE
"VocoOutlet object has no attribute adapter"

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway-addon-python#69]
I tried installing the Voco addon in the beta of 0.10.0 of the WebThings Gateway.

The add-on gets continuously rebooted, and this error shows up in the log.
`VocoOutlet object has no attribute adapter`

The add-on works fine under 0.9.0.

Could it be related to the voco-addon having the unusual construction where it's a sub-part of the `adapter` object? This was done to make it a hybrid add-on.

**Comment by mrstegeman** [comment]
This is definitely an issue with your add-on. In the gateway-addon library, outlets have no relation at all to adapters. They're attached to notifiers, not adapters.

**Comment by flatsiedatsie** [comment]
A more complete version of the error, for documentatiion.

```
2019-10-15 00:58:29.160 ERROR  : voco: Traceback (most recent call last):
2019-10-15 00:58:29.162 ERROR  : voco:   File "/home/pi/.mozilla-iot/addons/voco/main.py", line 40, in <module>
2019-10-15 00:58:29.163 ERROR  : voco:     _ADAPTER = VocoAdapter(verbose=True)
2019-10-15 00:58:29.165 ERROR  : voco:   File "/home/pi/.mozilla-iot/addons/voco/pkg/voco_adapter.py", line 363, in __init__
2019-10-15 00:58:29.166 ERROR  : voco:     self.notifier = VocoNotifier(self,self.voice_messages_queue,verbose=True) # TODO: It could be nice to move speech completely to a queue system so that voice never overlaps.
2019-10-15 00:58:29.167 ERROR  : voco:   File "/home/pi/.mozilla-iot/addons/voco/pkg/voco_notifier.py", line 40, in __init__
2019-10-15 00:58:29.168 ERROR  : voco:     self.handle_outlet_added(speak)
2019-10-15 00:58:29.170 ERROR  : voco:   File "/home/pi/.local/lib/python3.7/site-packages/gateway_addon/notifier.py", line 131, in handle_outlet_added
2019-10-15 00:58:29.171 ERROR  : voco:     self.manager_proxy.handle_outlet_added(outlet)
2019-10-15 00:58:29.172 ERROR  : voco:   File "/home/pi/.local/lib/python3.7/site-packages/gateway_addon/addon_manager_proxy.py", line 153, in handle_outlet_added
2019-10-15 00:58:29.173 ERROR  : voco:     'notifierId': outlet.adapter.id,
2019-10-15 00:58:29.175 ERROR  : voco: AttributeError: 'VocoOutlet' object has no attribute 'adapter'
```

I couldn't find any reference to an adapter variable in my code either. I suspect the `handle_outlet_added` method doesn't like the `speak` I'm sending it.

**Comment by flatsiedatsie** [comment]
> In the gateway-addon library, outlets have no relation at all to adapters.

Are you sure? It seems the gateway add-on is looking for outlet.adapter.id [in addon_manager_proxy.](https://github.com/mozilla-iot/gateway-addon-python/blob/1c6ce7f9185d2cb85e20c0d42188b34410726b1a/gateway_addon/addon_manager_proxy.py#L153)

**Comment by mrstegeman** [comment]
Ah!! That should be notifier, not adapter. Can you submit a PR?

**Comment by flatsiedatsie** [comment]
You mean in your code?
